export const Images = {
  cartIcon: require('./shopping-cart.png'),
  filterIcon: require('./filter.png'),
  searchIcon: require('./search.png'),
  coffee: require('./coffee.jpg'),
  star: require('./star.png'),
  menu: require('./smoothie.png'),
  heart: require('./heart.png'),
  coffeeIcon: require('./coffeeIcon.png'),
  home: require('./home.png'),
  user: require('./user.png'),
  emptyCart: require('./shopping.png'),
  leftIcon: require('./left.png'),
  coffeeBeans: require('./coffee-beans.png'),
  delivery: require('./delivery.png'),
  coffeeCup: require('./iced-coffee.png'),
  redHeart: require('./redheart.png'),
};
